---
# tasks file for basics
- name: get networking scripts
  apt:
#    name: netbase
    name: ifupdown
    state: present

- name: Set authorized key from git user
  authorized_key:
    user: root
    state: present
    key: https://github.com/bob5ec.keys
