---
# tasks file for basics
- name: get networking scripts
  apt:
#    name: netbase
    name: ifupdown
    state: present

- name: Set authorized key from git user
  authorized_key:
    user: root
    state: present
    key: https://github.com/bob5ec.keys

- cron:
    name: "register ansible-pull"
    minute: "1"
    job: "ansible-pull -U https://github.com/bob5ec/docker-infrastructure.git -C {{ env }} -o {{ playbook }} 2&>1 | logger -t ansible-pull"
