---
# tasks file for basics
- name: update packages once a day
  apt:
    update_cache: yes
    cache_valid_time: 86000


- name: install basic packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ifupdown
    - gnupg
    - rng-tools
    - git-crypt
    - aptitude
#    - apt-transport-https

- name: upgrade all packages and clean up the cache
  apt:
    upgrade: safe
    autoclean: yes
  notify: docker redeploy

- name: Create gpg batch file
  template:
    src: gpg-gen-key.batch.j2
    dest: /var/local/gpg-gen-key.batch

- name: Generate gpg key from bad entropy
  shell: "rngd -r /dev/urandom; gpg --batch --gen-key gpg-gen-key.batch; killall rngd; gpg -a --export {{ansible_hostname}} git-crypt > gpg.pub"
  args:
    chdir: /var/local
    creates: gpg.pub
  register: gpgpub
    #/dev/random does not have enough entropy and the CPU TRNG is backdoord so I use /dev/urandom. Please don't throw rocks at me...

  # TODO test keyserver behaviour if we upload this twice
  #- name: Send gpg key to keyserver
  #  shell: "gpg --keyserver pgp.mit.edu --send-key {{ansible_hostname}} git-crypt"
  #  when: gpgpub.changed
