---
driver:
  # using docker to test
  name: docker
  use_sudo: false
  privileged: true

#  instance_name: test
# remove all cached images
#  remove_images: true

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list of ansible galaxy requirements from the roles meta/main.yml
  requirements_path: requirements.yml

verifier:
  name: inspec
  
platforms:
#  - name: ubuntu-14.04
#  - name: debian-8.9

# kitchen-ansible is not installing ansible correctly on stable https://github.com/neillturner/kitchen-ansible/issues/257
  - name: debian-stable

suites:
  # suites found at /test/integration/$test-name
  - name: default
