---

#TODO move basics to task that requires them
- name: apply basic configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - basics

- name: configure and deploy libvirt
  hosts: all
  remote_user: root

  roles:
    - hypervisor

#TODO create vlan bridge interface within /etc/network/interfaces and connect the net to it
#auto dev
#iface dev inet manual
#        bridge_ports eth0.2
#        bridge_stp off
#        bridge_maxwait 0
#        bridge_fd 0

# [WARNING]: It is unnecessary to use '{{' in loops, leave variables in loop expressions bare.
#ERROR: [DEPRECATED]: include + with_items is a removed deprecated feature (in /etc/ansible/roles/dresden-weekly.network-interfaces/handlers/main.yml).  Please update your playbooks.


#TODO https://github.com/dresden-weekly/ansible-network-interfaces/issues/61
- name: create VLANs and network interfaces
  hosts: all
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod

  roles:
    - role: dresden-weekly.network-interfaces
      network_manage_devices: yes

      network_interfaces:
#      - device: vlan{{ item }}
      - device:
        name: vlan{{ item }}
        description: "{{ item }} VLAN"
        method: manual
#        address: 10.1.1.2
#        netmask: 24
#        broadcast: 10.1.1.255
        vlan:
          raw-device: eth0
        with_items: "{{ envs }}"
#        with_items:
#          - dev
#          - qa
#          - prod
      - device:
        name: "{{ item }}"
        description: "{{ item }} Network to attach VMs"
        method: manual
        bridge:
          ports: vlan{{ item }}
          stp: off
          maxwait: 0
          fd: 0
        with_items: "{{ envs }}"
#        with_items:
#          - dev
#          - qa
#          - prod


#      - device: vlanqa
#        method: manual
#        vlan:
#          raw-device: eth0
#      - device: vlanprod
#        method: manual
#        vlan:
#          raw-device: eth0
#      - device: {{ item }}
#        description: dev Network to attach VMs
#        method: manual
#        bridge:
#          ports: vlanDev
#          stp: off
#          maxwait: 0
#          fd: 0
#      - device: qa
#        method: manual
#        bridge:
#          ports: vlanQa
#          stp: off
#          maxwait: 0
#          fd: 0
#      - device: prod
#        method: manual
#        bridge:
#          ports: vlanProd
#          stp: off
#          maxwait: 0
#          fd: 0



#
#- name: deploy MySQL and configure the databases
#  hosts: vm
#  remote_user: root
#
#  roles:
#    - vm
