---
 
#TODO move basics to task that requires them
- name: apply basic configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - basics
  handlers:
    - include: roles/docker/handlers/main.yml

- name: configure and deploy libvirt
  hosts: metal
  remote_user: root

  roles:
    - hypervisor

#TODO create vlan bridge interface within /etc/network/interfaces and connect the net to it
#auto dev
#iface dev inet manual
#        bridge_ports eth0.2
#        bridge_stp off
#        bridge_maxwait 0
#        bridge_fd 0

# [WARNING]: It is unnecessary to use '{{' in loops, leave variables in loop expressions bare.
#ERROR: [DEPRECATED]: include + with_items is a removed deprecated feature (in /etc/ansible/roles/dresden-weekly.network-interfaces/handlers/main.yml).  Please update your playbooks.


#TODO https://github.com/dresden-weekly/ansible-network-interfaces/issues/61
- name: create VLANs and network interfaces
  hosts: metal
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod

    #nic: enp0s31f6
  roles:
    - role: dresden-weekly.network-interfaces
      network_manage_devices: yes

      network_interfaces:
#TODO test
      - device: enp0s31f6
        description: physical NIC
        auto: true
        family: inet
        #method: dhcp
        #VLAN interfaces using physical NIC as trunk
      - device: vlan3
        method: manual
        vlan:
          raw-device: enp0s31f6
      - device: vlan4
        method: manual
        vlan:
          raw-device: enp0s31f6
      - device: vlan5
        method: static
        address: 192.168.5.2
        gateway: 192.168.5.1
        netmask: 24
        vlan:
          raw-device: enp0s31f6
#TODO test
        #networks to attach VMs
      - device: dev
        method: manual
        bridge:
          ports: vlan3
          stp: off
          maxwait: 0
          fd: 0
      - device: qa
        method: manual
        bridge:
          ports: vlan4
          stp: off
          maxwait: 0
          fd: 0
      - device: prod
        method: manual
        bridge:
          ports: vlan5
          stp: off
          maxwait: 0
          fd: 0



- name: set up VM
  hosts: vm
  remote_user: root
  roles:
    - vms-guest
    - docker
