---
- name: apply only basic configuration
  hosts: all
  remote_user: root

  roles:
# applies to metal and vm
#TODO change to extra args variables:
    - { role: basics, deploy_env: "dev" , deploy_playbook: "hardware.yml" }

