---
#import_playbook: default.yml
- include: default.yml

- name: provision VMs with CoreOS container linux
  hosts: all
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod

  roles:
    - { role: vms, env: "dev",   network: "192.168.3" }
    - { role: vms, env: "qa" ,   network: "192.168.4" }
    - { role: vms, env: "prod" , network: "192.168.5" }
