---
#import_playbook: default.yml
- include: default.yml

- name: provision VMs with CoreOS container linux
  hosts: all
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod

  roles:
    - vms
