---
- include: default.yml

- name: provision dev VM
  hosts: metal
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod
  roles:
    - { role: vms, env: "dev",   network: "192.168.3" }

#TODO variables from first run re used in second run of the task
- name: provision qa VM
  hosts: metal
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod
  roles:
    - { role: vms, env: "qa",   network: "192.168.4" }

- name: provision prod VM
  hosts: metal
  remote_user: root
  vars:
    envs:
      - dev
      - qa
      - prod
  roles:
    - { role: vms, env: "prod",   network: "192.168.5" }
