# find the dependencies to list in meta/main.
# If there are non, remove this file and the reference to it in .kitchen.yml
# Otherwise should look something like below:
#
---
# - src: noqcks.apt-repository
 - src: debops.libvirt
 - src: debops.libvirtd
 - src: debops.apt_preferences
 - src: debops.ferm
 - src: debops.libvirtd_qemu
