#!/bin/bash
env=`grep -Eo '([A-Za-z]+)' /etc/hostname`
repo="https://github.com/bob5ec/running-docker-stack.git"
target="~/.running_docker_stack"

if [ ! -d "$target" ]; then
	git clone -b $env $repo $target
	cd $target
else
	cd $target
	git pull
fi

for compose in *.yml; do
	#use every yml as compose file and project name
	docker-compose -f $compose -p `basename $compose .yml` down
	docker-compose -f $compose -p `basename $compose .yml` up -d
done
