---
# tasks file for hypervisor


- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: get locales
  apt:
    name: locales
    state: present

- locale_gen:
    name: en_US.UTF-8
    state: present

- name: get libvirt
  apt:
    name: libvirt-daemon-system
    state: present

- service:
    name: libvirtd
    state: started
  #  enabled: yes

- cron:
    name: "register ansible-pull from branch master for the hardware playbook"
    minute: "15"
    job: "ansible-pull -U https://github.com/bob5ec/docker-infrastructure.git -C master -o hardware.yml 2&>1 | logger -t ansible-pull"
