---
#- name: Who is calling
#  debug: "msg=env:{{env}}item.item:{{item.item}}"

- name: Compile yml to ign
  shell: "ct -in-file {{env}}{{item.item}}.yml -out-file {{env}}{{item.item}}.ign"
  args:
    chdir: /var/lib/libvirt/images/
#    creates: "{{env}}{{item.item}}.ign"

- name: Reset Container Linux
  virt:
    name: "{{env}}{{item.item}}"
    state: shutdown

- name: wait for VM to shut down
  pause:
    seconds: 3
##TODO this notify does not trigger...
##- name: wait for VM to shut down
##  wait_for:
##    host: 192.168.3.2
##    port: 22
##    state: stopped

- name: Clean disk
  file:
    state: absent
    path: "/var/lib/libvirt/images/{{env}}{{item.item}}.qcow2"

- name: Create qcow2 disk
  shell: qemu-img create -f qcow2 -b coreos_production_qemu_image.img "{{env}}{{item.item}}.qcow2"
  args:
    chdir: /var/lib/libvirt/images/
#    creates: "{{env}}{{item.item}}.qcow2"

- name: run VM
  virt:
    name: "{{env}}{{item.item}}"
    state: running

- name: wait for VM to start and etcd to sync
  pause:
    seconds: 3
