---
# tasks file for docker
- name: get apt htts support
  apt:
    name: apt-transport-https

- name: Add docker package signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Set up Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Get docker-engine
  apt:
    name: docker-ce
    state: present

- name: Deploy docker Compose
  copy:
    src: "{{ role_path }}/files/docker-compose"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Deploy simple deployer
  copy:
    src: "{{ role_path }}/files/docker-deploy"
    dest: /usr/local/sbin/docker-deploy
    mode: 0755

- name: Register deployer in cron
  cron:
    minute: "33"
    job: "/usr/local/sbin/docker-deploy"
