---
# tasks file for docker
- name: get apt htts support
  apt:
    name: apt-transport-https

- name: Add docker package signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Set up Docker apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-stretch main
          #repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Get docker-engine
  apt:
    name: docker-engine
    state: present
    update_cache: yes

- name: Deploy simple deployer
  copy:
    src: "{{ role_path }}/files/docker-deploy"
    dst: /usr/local/sbin/docker-deploy

- name: Register deployer in cron
  cron:
    minute: "33"
    job: "/usr/local/sbin/docker-deploy"
