#!/bin/bash

echo "------------------------------"
echo "BOOTSTRAP FOR $1 IS RUNNING"

#TODO use etcd locking in the future
if ! [ "$NODE_NUMBER" = "1" ]; then
  while ! [ "`etcdctl get /swarm/first_manager`" ]; do
    echo "An other node is bootstrapping, waiting 5 seconds..."
    sleep 5
  done
fi

export PATH="$PATH:/opt/bin"

set -o allexport
source /etc/custom-environment
set +o allexport

slack -m "_${COREOS_PRIVATE_IPV4}_: Bootstraping a *$1* node" -u $SLACK_WEBHOOK_URL -c "#$SLACK_CHANNEL"

join-swarm-cluster $1

slack -m "_${COREOS_PRIVATE_IPV4}_: Bootstrap completed for *$1* node at ${COREOS_PRIVATE_IPV4}!" -u $SLACK_WEBHOOK_URL -c "#$SLACK_CHANNEL"
echo "BOOTSTRAP FOR $1 COMPLETED"
echo "------------------------------"
