#!/bin/bash
source /etc/custom-environment
TARGET="/etc/running_docker_stack_repo"
# run deploy only on one node
if [ "$NODE_NUMBER" = "1" ]; then

	if [ ! -d "$TARGET" ]; then
		git clone -b $env $running_docker_stack_repo $TARGET
		cd $TARGET
	else
		cd $TARGET
		git pull
	fi

	for compose in *.yml; do
		docker stack deploy --compose-file $compose `basename $compose .yml`
	done
fi
